version: '3'
services:
  flaskserver:
    container_name: flaskServer
    image: emiliodallas/flaskserver:flaskHilab  # Update this with your Flask app image details
    volumes:
      - myvolume:/app/Shared
    networks:
      - mynetwork
    ports:
      - 5000:5000
    
  streamlit:
    container_name: frontStreamlit
    image: emiliodallas/flaskserver:streamlitHilab  # Update this with your Streamlit app image details
    volumes:
      - myvolume:/app/Shared
    networks:
      - mynetwork
    ports:
      - 8501:8501

  postgres:
    container_name: postgresql
    image: postgres:latest  # Using the official PostgreSQL image
    restart: always
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    
  sql: 
    container_name: schema
    image: emiliodallas/flaskserver:databaseHilab  # Update this with your database schema image details
    depends_on:
      - postgres
    restart: on-failure      
    volumes:
      - myvolume:/app/Shared
    networks:
      - mynetwork

volumes:
  myvolume:

networks:
  mynetwork:
