version: '3'
services:
  flaskserver:
    container_name: flaskServer
    image: emiliodallas/flaskserver:flaskHilab
    volumes:
      - myvolume:/app/Shared
    networks:
      - mynetwork
    ports:
      - 5000:5000
    restart: on-failure      

    
  streamlit:
    container_name: frontStreamlit
    image: emiliodallas/flaskserver:streamlitHilab
    volumes:
      - myvolume:/app/Shared
    networks:
      - mynetwork
    ports:
      - 8501:8501

  postgres:
    container_name: postgresql
    image: postgres:latest
    restart: always
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  myvolume:

networks:
  mynetwork:
